const CustomEmojis = [
    { name: "(pepe_deadpepe)", src: "/Emoji/pepe_DeadPepe.png" },
    { name: "(pepe_fighter)", src: "/Emoji/pepe_fighter.png" },
    { name: "(pepe_kekw_pain)", src: "/Emoji/pepe_kekw_pain.png" },
    { name: "(pepe_love)", src: "/Emoji/pepe_love.png" },
    { name: "(pepe_nervous)", src: "/Emoji/pepe_nervous.png" },
    { name: "(pepe_stonks)", src: "/Emoji/pepe_stonks.png" },
    { name: "(pepe_yay)", src: "/Emoji/pepe_yay.png" },
    { name: "(pepe_yes)", src: "/Emoji/pepe_yes.png" },
    { name: "(pepe_comfyblush)", src: "/Emoji/pepecomfyblush.png" },
    { name: "(Pepe_Crypto)", src: "/Emoji/PepeCrypto.png" },
    { name: "(pepe_horny)", src: "/Emoji/pepehorny.png" },
    { name: "(pepe_OK)", src: "/Emoji/pepeOK.png" },
    { name: "(pepe_searching)", src: "/Emoji/pepesearching.png" },
    { name: "(pepe_think)", src: "/Emoji/pepethink.png" },
    { name: "(pepe_5head)", src: "/Emoji/pepe_5head.png" },
    { name: "(pepe_clown)", src: "/Emoji/pepe_clown.png" },
    { name: "(Pepe_NoHappy)", src: "/Emoji/PepeNoHappy.gif" },
    { name: "(Pepe_Clapping)", src: "/Emoji/PepeClapping.gif" },
    { name: "(pepe_money)", src: "/Emoji/Pepe_Moneyrain.gif" },
    { name: "(smileyface)", src: "/Emoji/smileyface.png" },
    { name: "(stonks)", src: "/Emoji/stonks.png" },
    { name: "(stonks_not)", src: "/Emoji/stonks_not.gif" },
    { name: "(wut)", src: "/Emoji/wut.png" },
    { name: "(catnekocatsip)", src: "/Emoji/catnekocatsip.png" },
    { name: "(doge_kek)", src: "/Emoji/doge_kek.png" },
    { name: "(pump)", src: "/Emoji/pump.png" },
    { name: "(dump)", src: "/Emoji/dump.png" },
    { name: "(joe_sus)", src: "/Emoji/joe_sus.png" },
    { name: "(kekw)", src: "/Emoji/kekw.png" },
    { name: "(kekw_leo)", src: "/Emoji/kekw_leo.png" },
    { name: "(kekw_W_dicaprio)", src: "/Emoji/kekw_W_dicaprio.png" },
    { name: "(kekw_pepe)", src: "/Emoji/kekw_pepe.png" },
  ];
  
  export default CustomEmojis;
  